print("========================================")
print("PROGRAMA DE ")
print("========================================")
nombre=input("Ingrese su nombre: ")
print("Hola como estas: ",nombre)
precio=15.50
producto=str(input("Ingrese su producto: "))
cantidad=float(input("Ingrese la cantidad: "))
total=(precio*cantidad)
print("El costo total es: ",total)
print("::::::::::::::::::::::::::::::::::::::::::::::::")