print("PROGRAMAS DE CALCULO DE SALARIO MENSUAL")
print("=======================================")
H=int(input("ingrese la cantidad de horas: "))
C=float(input("ingrese el costo por hora: "))
pago=(H*C)
print("el monto acumulado es : ",pago)
